# Name of Action
name: sleep

# Controls when the action will run. 
on:
  
  # If you want to trigger this on push to a branch uncomment below
  # push:
  #  branches: [ main ]
  
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Below this are each of the steps that are run
    steps:
          
      # sleep for 5 minutes 
      - name: Wait 5 minutes
        run: |
          n=1
          while [ $n -lt 300 ]
          do
          sleep 1s
          echo "Sleeping for $n seconds"
          echo " "
          ((n=$n+1))
          done
